### PR TITLE
penne: serve and dump commands

### PR DESCRIPTION
**Pull request by amery**

### CODE REVIEW

**Review by karasz — CHANGES_REQUESTED** [review]
Can you please add signal handling too? That should be needed in order to properly implement some features like dump the config or re-read the config

**Comment by amery** [comment]
> Can you please add signal handling too? That should be needed in order to properly implement some features like dump the config or re-read the config

That's managed by sidecar.Server which isn't integrated yet. Penne's Server.Listen() fails immediately with a `core.ErrNotImplemented` error at the point of this PR.

My goal with this PR is agreeing a cmd structure to be then applied to all other darvaza servers

**Comment by amery** [comment]
parked in favour of #7

**Comment by amery** [comment]
rebased and unlocked

**Review by karasz — APPROVED** [review]
LGTM

**Pull request merged**
