### PR TITLE
resolver: integrate suffixes

### PR DESCRIPTION
**Pull request by amery**

### CODE REVIEW

**Review by karasz — COMMENTED** [review]
I am on the fence with this. In order to be sure I would use `dns.IsFqdn`, `dns.CanonicalName` treating `DNS` `labels` as normal text is risky. Also integration with [PublicSuffixes](https://publicsuffix.org/list/public_suffix_list.dat) would be nice I guess

**Comment by amery** [comment]
> I am on the fence with this. In order to be sure I would use `dns.IsFqdn`, `dns.CanonicalName` treating `DNS` `labels` as normal text is risky. Also integration with [PublicSuffixes](https://publicsuffix.org/list/public_suffix_list.dat) would be nice I guess

I see suffixes here as patterns to decide if the resolver rules should be applied or not and compiled as glob using `.` as delimiter. I do believe it is handling the trailing dot correctly. where do you see the risk? @karasz 
not sure how to integrate publicsuffixes. could you expand on that? @karasz

**Review by karasz — APPROVED** [review]
ok

**Comment by amery** [comment]
> ok

eh? @karasz

**Comment by karasz** [comment]
> > ok
> 
> eh? @karasz

it is fit for purpose. Integrating PublicSufixes is the job of another PR, and what the code does now is enough.

**Comment by amery** [comment]
`v0.1.1` tagged

**Pull request merged**
