### PR TITLE
penne: add initial cobra and logger integration

### PR DESCRIPTION
**Pull request by amery**

### CODE REVIEW

**Comment by amery** [comment]
fixed typo

**Review by karasz — DISMISSED** [review]
LGTM

**Comment by karasz** [comment]
rebase?

**Review by karasz — APPROVED** [review]
LGTM

**Review by karasz — APPROVED** [review]

**Review by karasz — APPROVED** [review]
ok

**Review by karasz — APPROVED** [review]

**Review by amery — COMMENTED** [review]
I can't approve my own PRs :sob:

**Pull request merged**
